import { SvgColor } from '../../../components/svg-color';

const getIcon = (name) => <SvgColor src={`/assets/icons/navbar/${name}.svg`} sx={{ width: 1, height: 1 }} />;

export const ICONS = {
  blog: getIcon('ic_blog'),
  cart: getIcon('ic_cart'),
  chat: getIcon('ic_chat'),
  mail: getIcon('ic_mail'),
  user: getIcon('ic_user'),
  file: getIcon('ic_file'),
  lock: getIcon('ic_lock'),
  label: getIcon('ic_label'),
  blank: getIcon('ic_blank'),
  kanban: getIcon('ic_kanban'),
  folder: getIcon('ic_folder'),
  banking: getIcon('ic_banking'),
  booking: getIcon('ic_booking'),
  invoice: getIcon('ic_invoice'),
  calendar: getIcon('ic_calendar'),
  disabled: getIcon('ic_disabled'),
  external: getIcon('ic_external'),
  menuItem: getIcon('ic_menu_item'),
  ecommerce: getIcon('ic_ecommerce'),
  analytics: getIcon('ic_analytics'),
  dashboard: getIcon('ic_dashboard'),
  saleAndMarketing: getIcon('ic_kanban'),
  salary: getIcon('ic_ecommerce'),
  customer: <SvgColor src={`/assets/icons/navbar/customer-feedback.png`} sx={{ width: 1, height: 1 }} />,
  detail: getIcon('ic_booking'),
  inventory: <SvgColor src={`/assets/icons/navbar/inventory.png`} sx={{ width: 1, height: 1 }} />,
  priceList: <SvgColor src={`/assets/icons/navbar/report.png`} sx={{ width: 1, height: 1 }} />,
  orderList: <SvgColor src={`/assets/icons/navbar/shopping-list.png`} sx={{ width: 1, height: 1 }} />,
  truck: <SvgColor src={`/assets/icons/navbar/truck.png`} sx={{ width: 1, height: 1 }} />,
  fastDelivery: <SvgColor src={`/assets/icons/navbar/fast-delivery.png`} sx={{ width: 1, height: 1 }} />,
  freight: <SvgColor src={`/assets/icons/navbar/freight.png`} sx={{ width: 1, height: 1 }} />,
  shippingCost: <SvgColor src={`/assets/icons/navbar/shipping-cost.png`} sx={{ width: 1, height: 1 }} />,
  kilogram: <SvgColor src={`/assets/icons/navbar/weighting.png`} sx={{ width: 1, height: 1 }} />,
  truckManagement: <SvgColor src={`/assets/icons/navbar/recycling-truck.png`} sx={{ width: 1, height: 1 }} />,
  forklift: <SvgColor src={`/assets/icons/navbar/forklift.png`} sx={{ width: 1, height: 1 }} />,
  driver: <SvgColor src={`/assets/icons/navbar/driving-license.png`} sx={{ width: 1, height: 1 }} />,
  route: <SvgColor src={`/assets/icons/navbar/route.png`} sx={{ width: 1, height: 1 }} />,
  note: <SvgColor src={`/assets/icons/navbar/note.png`} sx={{ width: 1, height: 1 }} />,
};
