// ----------------------------------------------------------------------

export const fullAddress = [
  'Số 1, Đường 1, Quận 1, Thành phố Hồ Chí Minh',
  'Số 2, Đường 2, Hà Nội',
  'Số 3, Đường AAA1, Quận XYZ, Hà Nội',
  'Số 4, Đường AAA2, Quận XYZ, Hà Nội',
  'Số 5, Đường AAA3, Quận XYZ, Hà Nội',
  'Số 6, Đường AAA4, Quận XYZ, Hà Nội',
  'Số 7, Đường AAA5, Quận XYZ, Hà Nội',
  'Số 8, Đường AAA6, Quận XYZ, Hà Nội',
  'Số 9, Đường AAA7, Quận XYZ, Hà Nội',
  'Số 10, Đường AAA8, Quận XYZ, Hà Nội',
  'Số 11, Đường AAA9, Quận XYZ, Hà Nội',
  'Số 12, Đường AAA10, Quận XYZ, Hà Nội',
  'Số 13, Đường AAA11, Quận XYZ, Hà Nội',
  'Số 14, Đường AAA12, Quận XYZ, Hà Nội',
  'Số 15, Đường AAA13, Quận XYZ, Hà Nội',
  'Số 16, Đường AAA14, Quận XYZ, Hà Nội',
  'Số 17, Đường AAA15, Quận XYZ, Hà Nội',
  'Số 18, Đường AAA16, Quận XYZ, Hà Nội',
  'Số 19, Đường AAA17, Quận XYZ, Hà Nội',
  'Số 20, Đường AAA18, Quận XYZ, Hà Nội',
  'Số 21, Đường AAA19, Quận XYZ, Hà Nội',
  'Số 22, Đường AAA12, Quận XYZ, Hà Nội',
  'Số 23, Đường AAA, Quận XYZ, Hà Nội',
  'Số 24, Đường AAA, Quận XYZ, Hà Nội',
  'Số 25, Đường AAA, Quận XYZ, Hà Nội',
  'Số 26, Đường AAA, Quận XYZ, Hà Nội',
  'Số 27, Đường AAA, Quận XYZ, Hà Nội',
  'Số 28, Đường AAA, Quận XYZ, Hà Nội',
  'Số 29, Đường AAA, Quận XYZ, Hà Nội',
  'Số 30, Đường AAA, Quận XYZ, Hà Nội',
  'Số 31, Đường AAA, Quận XYZ, Hà Nội',
  'Số 32, Đường AAA, Quận XYZ, Hà Nội',
  'Số 33, Đường AAA, Quận XYZ, Hà Nội',
];

export const country = [
  'Kenya',
  'Madagascar',
  'Netherlands Antilles',
  'Azerbaijan',
  'Aruba',
  'Comoros',
  'Sierra Leone',
  'Bermuda',
  'Italy',
  'Iran',
  'Denmark',
  'Congo',
  'Cambodia',
  'Virgin Islands, British',
  'Bahamas',
  'Italy',
  'France',
  'Portugal',
  'Nepal',
  'Saint Vincent and the Grenadines',
  'Greenland',
  'Maldives',
  'Comoros',
  'Bhutan',
  'Tuvalu',
  'Ethiopia',
  'Myanmar',
  'Libyan Arab Jamahiriya',
  'Senegal',
  'Malta',
  'Kyrgyz Republic',
  'Turks and Caicos Islands',
  'Gibraltar',
  'Sweden',
  'Zambia',
  'Isle of Man',
  'Canada',
  'Turkey',
  'Samoa',
  'Vietnam',
];
