// ----------------------------------------------------------------------

export const fullName = [
  'Ngô Bảo An',
  'Đặng Hữu Ðạt',
  'Phan Huy Chiểu',
  'Lê Nghĩa Hòa',
  'Huỳnh Chí Anh',
  'Lê Ðức Ân',
  'Hàn Hữu Khanh',
  'Thái Chí Vịnh',
  'Trần Nam Hưng',
  'Dương Trí Thắng',
  'Chu Huy Hà',
  'Vưu Ðình Quảng',
  'Lý Hữu Khôi',
  'Hoàng Tuấn Việt',
  'Quyền Tường Phát',
  'Nguyễn Thế Sơn',
  'Nguyễn Việt Duy',
  'Nguyễn Chí Công',
  'Kim Bảo Châu',
  'Phùng Tuấn Trung',
];

export const firstName = [
  'An',
  'Ðạt',
  'Chiểu',
  'Hòa',
  'Anh',
  'Ân',
  'Khanh',
  'Vịnh',
  'Hưng',
  'Thắng',
  'Hà',
  'Quảng',
  'Khôi',
  'Việt',
  'Phát',
  'Sơn',
  'Duy',
  'Công',
  'Châu',
  'Trung',
];

export const lastName = [
  'Ngô Bảo',
  'Đặng Hữu',
  'Phan Huy',
  'Lê Nghĩa',
  'Huỳnh Chí',
  'Lê Ðức',
  'Hàn Hữu',
  'Thái Chí',
  'Trần Nam',
  'Dương Trí',
  'Chu Huy',
  'Vưu Ðình',
  'Lý Hữu',
  'Hoàng Tuấn',
  'Quyền Tường',
  'Nguyễn Thế',
  'Nguyễn Việt',
  'Nguyễn Chí',
  'Kim Bảo',
  'Phùng Tuấn',
];
